# Generated by Django 4.2.16 on 2024-10-13 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_profilemodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='profile_images/user.png', upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
