# Generated by Django 4.2.16 on 2024-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
