# Generated by Django 4.2.16 on 2024-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_offermodel_views_count_problemmodel_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='slug',
            field=models.SlugField(default='  ', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
    ]
