# Generated by Django 4.2.16 on 2024-10-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_offermodel_slug_problemmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='slug',
        ),
    ]
