# Generated by Django 4.2.16 on 2024-10-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_offermodel_options_remove_offermodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
    ]
